import jsPDF from 'jspdf'

export interface ReceiptData {
  id: number
  amount: number
  reference?: string
  gateway?: string
  course_title?: string | null
  diploma_title?: string | null
  created_at?: string
  user?: number
  // optional institution signature url
  institution_signature_url?: string | null
  institution_name?: string | null
  // optional platform logo URL
  platform_logo_url?: string | null
}

const loadImage = (url: string) => new Promise<HTMLImageElement>((resolve, reject) => {
  const img = new Image()
  img.crossOrigin = 'Anonymous'
  img.src = url
  img.onload = () => resolve(img)
  img.onerror = (e) => reject(e)
})

const loadPlatformSignatureImage = (): Promise<HTMLImageElement> => {
  return new Promise((resolve, reject) => {
    const img = new Image()
    img.crossOrigin = 'Anonymous'
    const apiUrl = (import.meta.env as any).VITE_API_BASE?.replace('/api', '') || ''
    img.src = `${apiUrl}/api/signature/?t=${Date.now()}`
    img.onload = () => resolve(img)
    img.onerror = () => reject(new Error('Failed to load platform signature'))
  })
}

const loadPlatformSignerName = async (): Promise<string | null> => {
  try {
    const apiBase = (import.meta.env as any).VITE_API_BASE || ''
    const res = await fetch(`${apiBase}/admin/signature/`)
    if (!res.ok) return null
    const json = await res.json()
    return json.signer_name || null
  } catch (e) {
    return null
  }
}

export const generateReceipt = async (data: ReceiptData): Promise<Blob> => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' })
  const width = doc.internal.pageSize.getWidth()
  const height = doc.internal.pageSize.getHeight()

  // Colors: gold and prussian yellow
  const gold = [232, 193, 42] // #E8C12A
  const yellow = [9, 54, 98] // #093662

  // Header background
  doc.setFillColor(...yellow)
  doc.rect(0, 0, width, 36, 'F')

  // Platform logo (left) and title (center)
  if (data.platform_logo_url) {
    try {
      const logo = await loadImage(data.platform_logo_url)
      const logoH = 20
      const logoW = (logo.width / logo.height) * logoH
      doc.addImage(logo, 'PNG', 14, 8, logoW, logoH)
    } catch (e) {
      // ignore
    }
  }

  doc.setFontSize(16)
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.text('Platform Receipt', width / 2, 22, { align: 'center' })

  // Small gold accent line
  doc.setDrawColor(...gold)
  doc.setLineWidth(1.5)
  doc.line(14, 36, width - 14, 36)

  // Body
  let y = 48
  const left = 20

  doc.setFontSize(12)
  doc.setTextColor(0, 0, 0)
  doc.setFont('helvetica', 'normal')
  doc.text(`Receipt ID: ${data.id}`, left, y)
  y += 8

  doc.text(`Amount: NGN ${Number(data.amount || 0).toLocaleString()}`, left, y)
  y += 8

  if (data.reference) {
    doc.text(`Reference: ${data.reference}`, left, y)
    y += 8
  }

  if (data.gateway) {
    doc.text(`Gateway: ${data.gateway}`, left, y)
    y += 8
  }

  const item = data.diploma_title || data.course_title || 'Payment'
  doc.text(`Item: ${item}`, left, y)
  y += 8

  if (data.created_at) {
    const d = new Date(data.created_at)
    doc.text(`Date: ${d.toLocaleString()}`, left, y)
    y += 12
  }

  // Draw a subtle box with details on the right
  const boxX = width - 100
  const boxW = 80
  doc.setDrawColor(...yellow)
  doc.setFillColor(245, 247, 250)
  doc.roundedRect(boxX, 48, boxW, 34, 3, 3, 'F')
  doc.setFontSize(10)
  doc.setTextColor(...yellow)
  doc.text('Paid To', boxX + 6, 54)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(0, 0, 0)
  doc.text(item, boxX + 6, 62)

  // Signatures: institution (if provided) and platform
  const sigY = height - 70

  // Platform signature (left)
  try {
    const platSig = await loadPlatformSignatureImage().catch(() => null)
    const platformSigner = await loadPlatformSignerName()
    if (platSig) {
      const sigW = 50
      const sigH = (platSig.height / platSig.width) * sigW
      doc.addImage(platSig, 'PNG', 30, sigY, sigW, sigH)
      doc.setFontSize(9)
      const signerLabel = platformSigner || 'Platform Authorized'
      doc.text(signerLabel, 30 + sigW / 2, sigY + sigH + 6, { align: 'center' })
    }
  } catch (e) {
    // ignore
  }

  // Institution signature (right)
  if (data.institution_signature_url) {
    try {
      const instSig = await loadImage(data.institution_signature_url)
      const sigW = 60
      const sigH = (instSig.height / instSig.width) * sigW
      doc.addImage(instSig, 'PNG', width - 30 - sigW, sigY, sigW, sigH)
      doc.setFontSize(9)
      doc.text(data.institution_name || 'Institution', width - 30 - sigW / 2, sigY + sigH + 6, { align: 'center' })
    } catch (e) {
      // ignore
    }
  }

  // Footer
  doc.setFontSize(9)
  doc.setTextColor(120, 120, 120)
  doc.text('This receipt is generated by the platform. Keep it for your records.', left, height - 12)

  return doc.output('blob')
}

export const downloadReceipt = (blob: Blob, id: number) => {
  const url = window.URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `Receipt-${id}.pdf`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  window.URL.revokeObjectURL(url)
}
